export const championMap: Record<string, string> = {
  'エイトロックス': 'Aatrox',
  'アーリ': 'Ahri',
  'アカリ': 'Akali',
  'アクシャン': 'Akshan',
  'アリスター': 'Alistar',
  'アンベッサ': 'Ambessa',
  'アムム': 'Amumu',
  'アニビア': 'Anivia',
  'アニー': 'Annie',
  'アフェリオス': 'Aphelios',
  'アッシュ': 'Ashe',
  'オレリオン・ソル': 'AurelionSol',
  'オーロラ': 'Aurora',
  'アジール': 'Azir',
  'バード': 'Bard',
  'ベル＝ヴェス': 'Belveth',
  'ブリッツクランク': 'Blitzcrank',
  'ブランド': 'Brand',
  'ブラウム': 'Braum',
  'ブライアー': 'Briar',
  'ケイトリン': 'Caitlyn',
  'カミール': 'Camille',
  'カシオペア': 'Cassiopeia',
  'チョ＝ガス': 'Chogath',
  'コーキ': 'Corki',
  'ダリウス': 'Darius',
  'ダイアナ': 'Diana',
  'ドレイヴン': 'Draven',
  'ドクター・ムンド': 'DrMundo',
  'エコー': 'Ekko',
  'エリス': 'Elise',
  'イブリン': 'Evelynn',
  'エズリアル': 'Ezreal',
  'フィドルスティックス': 'Fiddlesticks',
  'フィオラ': 'Fiora',
  'フィズ': 'Fizz',
  'ガリオ': 'Galio',
  'ガングプランク': 'Gangplank',
  'ガレン': 'Garen',
  'ナー': 'Gnar',
  'グラガス': 'Gragas',
  'グレイブス': 'Graves',
  'グウェン': 'Gwen',
  'ヘカリム': 'Hecarim',
  'ハイマーディンガー': 'Heimerdinger',
  'フェイ': 'Hwei',
  'イラオイ': 'Illaoi',
  'イレリア': 'Irelia',
  'アイバーン': 'Ivern',
  'ジャンナ': 'Janna',
  'ジャーヴァンⅣ': 'JarvanIV',
  'ジャックス': 'Jax',
  'ジェイス': 'Jayce',
  'ジン': 'Jhin',
  'ジンクス': 'Jinx',
  'カイ＝サ': 'Kaisa',
  'カリスタ': 'Kalista',
  'カルマ': 'Karma',
  'カーサス': 'Karthus',
  'カサディン': 'Kassadin',
  'カタリナ': 'Katarina',
  'ケイル': 'Kayle',
  'ケイン': 'Kayn',
  'ケネン': 'Kennen',
  'カ＝ジックス': 'Khazix',
  'キンドレッド': 'Kindred',
  'クレッド': 'Kled',
  'コグ＝マウ': 'KogMaw',
  'カ・サンテ': 'KSante',
  'ルブラン': 'Leblanc',
  'リー・シン': 'LeeSin',
  'レオナ': 'Leona',
  'リリア': 'Lillia',
  'リサンドラ': 'Lissandra',
  'ルシアン': 'Lucian',
  'ルル': 'Lulu',
  'ラックス': 'Lux',
  'マルファイト': 'Malphite',
  'マルザハール': 'Malzahar',
  'マオカイ': 'Maokai',
  'マスター・イー': 'MasterYi',
  'メル': 'Mel',
  'ミリオ': 'Milio',
  'ミス・フォーチュン': 'MissFortune',
  'ウーコン': 'MonkeyKing',
  'モルデカイザー': 'Mordekaiser',
  'モルガナ': 'Morgana',
  'ナフィーリ': 'Naafiri',
  'ナミ': 'Nami',
  'ナサス': 'Nasus',
  'ノーチラス': 'Nautilus',
  'ニーコ': 'Neeko',
  'ニダリー': 'Nidalee',
  'ニーラ': 'Nilah',
  'ノクターン': 'Nocturne',
  'ヌヌ＆ウィルンプ': 'Nunu',
  'オラフ': 'Olaf',
  'オリアナ': 'Orianna',
  'オーン': 'Ornn',
  'パンテオン': 'Pantheon',
  'ポッピー': 'Poppy',
  'パイク': 'Pyke',
  'キヤナ': 'Qiyana',
  'クイン': 'Quinn',
  'ラカン': 'Rakan',
  'ラムス': 'Rammus',
  'レク＝サイ': 'RekSai',
  'レル': 'Rell',
  'レナータ・グラスク': 'Renata',
  'レネクトン': 'Renekton',
  'レンガー': 'Rengar',
  'リヴェン': 'Riven',
  'ランブル': 'Rumble',
  'ライズ': 'Ryze',
  'サミーラ': 'Samira',
  'セジュアニ': 'Sejuani',
  'セナ': 'Senna',
  'セラフィーン': 'Seraphine',
  'セト': 'Sett',
  'シャコ': 'Shaco',
  'シェン': 'Shen',
  'シヴァーナ': 'Shyvana',
  'シンジド': 'Singed',
  'サイオン': 'Sion',
  'シヴィア': 'Sivir',
  'スカーナー': 'Skarner',
  'スモルダー': 'Smolder',
  'ソナ': 'Sona',
  'ソラカ': 'Soraka',
  'スウェイン': 'Swain',
  'サイラス': 'Sylas',
  'シンドラ': 'Syndra',
  'タム・ケンチ': 'TahmKench',
  'タリヤ': 'Taliyah',
  'タロン': 'Talon',
  'タリック': 'Taric',
  'ティーモ': 'Teemo',
  'スレッシュ': 'Thresh',
  'トリスターナ': 'Tristana',
  'トランドル': 'Trundle',
  'トリンダメア': 'Tryndamere',
  'ツイステッド・フェイト': 'TwistedFate',
  'トゥイッチ': 'Twitch',
  'ウディア': 'Udyr',
  'アーゴット': 'Urgot',
  'ヴァルス': 'Varus',
  'ヴェイン': 'Vayne',
  'ベイガー': 'Veigar',
  'ヴェル＝コズ': 'Velkoz',
  'ヴェックス': 'Vex',
  'ヴァイ': 'Vi',
  'ヴィエゴ': 'Viego',
  'ビクター': 'Viktor',
  'ブラッドミア': 'Vladimir',
  'ボリベア': 'Volibear',
  'ワーウィック': 'Warwick',
  'ザヤ': 'Xayah',
  'ゼラス': 'Xerath',
  'シン・ジャオ': 'XinZhao',
  'ヤスオ': 'Yasuo',
  'ヨネ': 'Yone',
  'ヨリック': 'Yorick',
  'ユナラ': 'Yunara',
  'ユーミ': 'Yuumi',
  'ザーヘン': 'Zaahen',
  'ザック': 'Zac',
  'ゼド': 'Zed',
  'ゼリ': 'Zeri',
  'ジグス': 'Ziggs',
  'ジリアン': 'Zilean',
  'ゾーイ': 'Zoe',
  'ザイラ': 'Zyra'
}

export function getChampionIcon(japaneseName: string): string {
  const englishName = championMap[japaneseName]
  if (!englishName) return ''
  return `https://ddragon.leagueoflegends.com/cdn/16.4.1/img/champion/${englishName}.png`
}

// 英語名→チャンピオンIDのマップ（Data Dragonから取得）
let championIdMap: Record<string, number> | null = null

export async function getChampionIdMap(): Promise<Record<string, number>> {
  if (championIdMap) return championIdMap
  const res = await fetch('https://ddragon.leagueoflegends.com/cdn/16.4.1/data/ja_JP/champion.json')
  const data = await res.json()
  const map: Record<string, number> = {}
  Object.values(data.data).forEach((champ: any) => {
    map[champ.id] = parseInt(champ.key)
  })
  championIdMap = map
  return map
}

// 日本語名→チャンピオンID
export async function getChampionId(japaneseName: string): Promise<number | null> {
  const englishName = championMap[japaneseName]
  if (!englishName) return null
  const idMap = await getChampionIdMap()
  return idMap[englishName] ?? null
}